### PR TITLE
Add queue config support

### PR DESCRIPTION
**Pull request by sevein**

### CODE REVIEW

**Comment by hakamine** [comment]
do we always need to use memcached with gearman? If yes, do we need to install/check if memcached is installed in this role ?

**Comment by sevein** [comment]
`gearman-job-server` installs `memcached` locally, but I could change that adding `install_recommends: no`. If I do so, I guess I could make the following changes:

`vars/defaults.yml`
```
# Override this as desired, e.g. --queue-type=libmemcached --libmemcached-servers=127.0.0.1:11211
queue_parameters: "--queue-type=builtin"
```

`templates/etc/defaults/gearman.yml`
```
PARAMS="--listen={{ gearman_bind_address }} --port={{ gearman_bind_port }} {{ queue_parameters }}"
```

How does that sound?

---

An alternative would be to take a dictionary, e.g.

```
---
- name: "Install ..."
  hosts: "gearman_server_1"
  roles:
    - name: "gearman"
      gearman_opts:
        listen: 127.0.0.1
        port: 11211
        queue-type: libmemcached
        libmemcached-servers: "host1:11211,host2:11211"
```

... and use that in `templates/etc/defaults/gearman.yml`, but I'm not sure how I can achieve that. There might be a j2 filter that we could use to iterate over the keys and values of `gearman_opts` but no idea...

**Comment by sevein** [comment]
It turns out that "/etc/init/gearman-job-server.conf" was not being populated at all and the old init.d script was not being used. So I've done the fixed explained above. Now using `builtin` queue and won't install memcached unless you explicitly ask.

I think that this is backward compatible as the default queue type is `builtin` anyways.

**Comment by sevein** [comment]
In `/etc/init/gearman-job-server.conf`I am voluntarily passing `stder`to `--log-file`, that way upstart will be the one managing the logs, which I think it's very convenient.

**Comment by hakamine** [comment]
There are two tasks in tasks/main.yml with the same name ("Populate gearman defaults"), but I guess that does not cause a problem?

**Comment by sevein** [comment]
Ops, sorry. Too many open fronts and I become erratic.

**Comment by hakamine** [comment]
I was about to ask why install only the package gearman-tools and gearman-job-server but not the package gearman, but it looks like the latter is only kind of a shortcut to install the other two.
:+1:

**Comment by sevein** [comment]
Yes, I figured it'd be better to be explicit, it's clearer. Thank you, I'll merge.

**Pull request merged**
